import { Player } from "@/types";

export const players: Player[] = [
  {
    id: 1,
    name: "Faker",
    game: "League of Legends",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Faker",
    ranking: 99,
    bio: "Legendary mid-laner, considered the GOAT of LoL.",
  },
  {
    id: 2,
    name: "Ninja",
    game: "Fortnite",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Ninja",
    ranking: 95,
    bio: "One of the most recognizable names in gaming.",
  },
  {
    id: 3,
    name: "Shroud",
    game: "Valorant",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Shroud",
    ranking: 92,
    bio: "Professional gamer known for his incredible aim.",
  },
  {
    id: 4,
    name: "s1mple",
    game: "CS:GO",
    avatar: "https://avatar.iran.liara.run/public/boy?username=s1mple",
    ranking: 98,
    bio: "Considered the best CS:GO player in history.",
  },
  {
    id: 5,
    name: "Doinb",
    game: "League of Legends",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Doinb",
    ranking: 90,
    bio: "World Champion and innovator in mid-lane strategies.",
  },
  {
    id: 6,
    name: "N0tail",
    game: "Dota 2",
    avatar: "https://avatar.iran.liara.run/public/boy?username=N0tail",
    ranking: 91,
    bio: "Two-time TI champion and one of Dota 2's best captains.",
  },
  {
    id: 7,
    name: "TenZ",
    game: "Valorant",
    avatar: "https://avatar.iran.liara.run/public/boy?username=TenZ",
    ranking: 88,
    bio: "Rising star in the Valorant scene.",
  },
  {
    id: 8,
    name: "ZywOo",
    game: "CS:GO",
    avatar: "https://avatar.iran.liara.run/public/boy?username=ZywOo",
    ranking: 96,
    bio: "Young prodigy known for his incredible skill.",
  },
  {
    id: 9,
    name: "Doublelift",
    game: "League of Legends",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Doublelift",
    ranking: 87,
    bio: "Legendary ADC with multiple championships.",
  },
  {
    id: 10,
    name: "Froppy",
    game: "Overwatch",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Froppy",
    ranking: 85,
    bio: "Versatile player known for adaptability.",
  },
  {
    id: 11,
    name: "ClutchGod",
    game: "PUBG",
    avatar: "https://avatar.iran.liara.run/public/boy?username=ClutchGod",
    ranking: 89,
    bio: "Known for clutch performances in high-stakes matches.",
  },
  {
    id: 12,
    name: "KennyS",
    game: "CS:GO",
    avatar: "https://avatar.iran.liara.run/public/boy?username=KennyS",
    ranking: 94,
    bio: "A sniper known for his quick reflexes.",
  },
  {
    id: 13,
    name: "Jankos",
    game: "League of Legends",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Jankos",
    ranking: 86,
    bio: "One of the most experienced junglers in LoL.",
  },
  {
    id: 14,
    name: "B0aty",
    game: "Runescape",
    avatar: "https://avatar.iran.liara.run/public/boy?username=B0aty",
    ranking: 80,
    bio: "Popular streamer known for his educational content.",
  },
  {
    id: 15,
    name: "Raven",
    game: "Dota 2",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Raven",
    ranking: 90,
    bio: "Talented carry player with great mechanics.",
  },
  {
    id: 16,
    name: "SonicFox",
    game: "Mortal Kombat",
    avatar: "https://avatar.iran.liara.run/public/boy?username=SonicFox",
    ranking: 99,
    bio: "Fighting game champion known for multiple titles.",
  },
  {
    id: 17,
    name: "Riot",
    game: "Apex Legends",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Riot",
    ranking: 85,
    bio: "Apex Legends professional known for his skills.",
  },
  {
    id: 18,
    name: "Fallen",
    game: "CS:GO",
    avatar: "https://avatar.iran.liara.run/public/boy?username=Fallen",
    ranking: 93,
    bio: "One of the best AWPers in the CS:GO scene.",
  },
  {
    id: 19,
    name: "GeT_RiGhT",
    game: "CS:GO",
    avatar: "https://avatar.iran.liara.run/public/boy?username=GeT_RiGhT",
    ranking: 88,
    bio: "A legendary player known for his clutch plays.",
  },
  {
    id: 20,
    name: "KuroKy",
    game: "Dota 2",
    avatar: "https://avatar.iran.liara.run/public/boy?username=KuroKy",
    ranking: 92,
    bio: "Legendary support player and multiple TI champion.",
  },
];
